#!/usr/bin/env bash
# vandine-pi3.sh — One-shot deploy script for a remote node.
# Run as the normal user (not root). Sudo is used only where needed.
#
# What this does:
#   1. Install RNS (rns) and psutil via pip
#   2. Copy suite files into ~/reticulum-mesh/
#   3. Write ~/.reticulum/config with TCPClientInterface → hub
#   4. Create and enable systemd user services: rns-beacon + rns-rexec
#
# Usage: HUB_HOST=<hub_tailscale_ip> HUB_PORT=4242 bash setup/vandine-pi3.sh
#        (run from the reticulum-mesh project root, or adjust SUITE_DIR below)

set -euo pipefail

PI2_HOST="${HUB_HOST:?Set HUB_HOST to your hub node Tailscale IP}"
PI2_PORT="${HUB_PORT:-4242}"
SUITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_DIR="$HOME/reticulum-mesh"
RNS_CONFIG_DIR="$HOME/.reticulum"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"

echo "=== Vandine Pi3 deploy ==="
echo "Suite source : $SUITE_DIR"
echo "Deploy target: $DEPLOY_DIR"
echo "Pi2 hub      : $PI2_HOST:$PI2_PORT"
echo

# ── 1. Dependencies ───────────────────────────────────────────────────
echo "[1/4] Installing Python dependencies..."
pip3 install --quiet --user --break-system-packages rns psutil \
  || pip3 install --quiet --user rns psutil
echo "      rns and psutil installed."

# ── 2. Copy suite ─────────────────────────────────────────────────────
echo "[2/4] Copying suite files to $DEPLOY_DIR..."
mkdir -p "$DEPLOY_DIR/lib" "$DEPLOY_DIR/config"

for f in beacon.py rexec.py monitor.py chat.py discover.py; do
    if [[ -f "$SUITE_DIR/$f" ]]; then
        cp "$SUITE_DIR/$f" "$DEPLOY_DIR/$f"
        echo "      copied $f"
    else
        echo "      WARNING: $f not found in $SUITE_DIR — skipping"
    fi
done

for f in lib/common.py lib/identity.py lib/__init__.py; do
    if [[ -f "$SUITE_DIR/$f" ]]; then
        cp "$SUITE_DIR/$f" "$DEPLOY_DIR/$f"
        echo "      copied $f"
    fi
done

if [[ -f "$SUITE_DIR/config/rns-tcp-client.conf" ]]; then
    cp "$SUITE_DIR/config/rns-tcp-client.conf" "$DEPLOY_DIR/config/"
fi

# ── 3. RNS config ─────────────────────────────────────────────────────
echo "[3/4] Writing Reticulum config..."
mkdir -p "$RNS_CONFIG_DIR"

if [[ -f "$RNS_CONFIG_DIR/config" ]]; then
    echo "      ~/.reticulum/config already exists — backing up to config.bak"
    cp "$RNS_CONFIG_DIR/config" "$RNS_CONFIG_DIR/config.bak"
fi

cat > "$RNS_CONFIG_DIR/config" << EOF
# Reticulum config for Pi3 (Vandine)
# Generated by vandine-pi3.sh

[reticulum]
  enable_transport = False
  share_instance = Yes
  shared_instance_port = 37428
  instance_control_port = 37429
  panic_on_interface_error = No

[logging]
  loglevel = 4

[interfaces]

  [[RNS TCP Client]]
    type = TCPClientInterface
    enabled = yes
    target_host = ${PI2_HOST}
    target_port = ${PI2_PORT}
EOF

echo "      ~/.reticulum/config written."

# ── 4. Systemd user services ──────────────────────────────────────────
echo "[4/4] Installing systemd user services..."
mkdir -p "$SYSTEMD_USER_DIR"

PYTHON="$(which python3)"

cat > "$SYSTEMD_USER_DIR/rns-beacon.service" << EOF
[Unit]
Description=Reticulum Mesh Beacon (Pi3 Vandine)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${DEPLOY_DIR}
ExecStart=${PYTHON} ${DEPLOY_DIR}/beacon.py --interval 60
Restart=always
RestartSec=15
Environment=PYTHONPATH=${DEPLOY_DIR}

[Install]
WantedBy=default.target
EOF

cat > "$SYSTEMD_USER_DIR/rns-rexec.service" << EOF
[Unit]
Description=Reticulum Mesh Remote Exec Daemon (Pi3 Vandine)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${DEPLOY_DIR}
ExecStart=${PYTHON} ${DEPLOY_DIR}/rexec.py serve
Restart=always
RestartSec=15
Environment=PYTHONPATH=${DEPLOY_DIR}

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now rns-beacon.service
systemctl --user enable --now rns-rexec.service

echo
echo "=== Deploy complete ==="
echo
echo "Service status:"
systemctl --user status rns-beacon.service --no-pager -l 2>/dev/null | head -8 || true
echo
systemctl --user status rns-rexec.service --no-pager -l 2>/dev/null | head -8 || true
echo
echo "Beacon address (wait ~10s for RNS to start):"
sleep 5
journalctl --user -u rns-beacon.service --no-pager -n 5 2>/dev/null | grep -E "Address:|Beacon started" || true
echo
echo "Next steps on ThinkStation:"
echo "  python3 discover.py          # wait for Pi3 to appear"
echo "  python3 monitor.py --add pi3 <hash>"
echo "  python3 monitor.py           # Pi3 should appear in dashboard"
